name: Main Workflow
on: [push, pull_request]
jobs:
  test-elixir:
    runs-on: ubuntu-latest
    container: elixir:${{ matrix.elixir_version }}-slim

    strategy:
      matrix:
        elixir_version: ["1.11"]

    steps:
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install --no-install-recommends -y git make gcc
          apt-get clean
          rm -rf /var/lib/apt/lists/*
          mix local.rebar --force
          mix local.hex --force

      - uses: actions/checkout@v2

      - name: Install mix dependencies
        run: mix deps.get

      - run: mix test
